ALTER TABLE "customer_rules" ADD CONSTRAINT "customer_rules_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_entries" ADD CONSTRAINT "daily_entries_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_entries" ADD CONSTRAINT "daily_entries_company_firm_isolation_fk" FOREIGN KEY ("company_id","firm_id") REFERENCES "public"."companies"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_entries" ADD CONSTRAINT "daily_entries_truck_firm_isolation_fk" FOREIGN KEY ("truck_id","firm_id") REFERENCES "public"."trucks"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_entries" ADD CONSTRAINT "daily_entries_from_location_firm_isolation_fk" FOREIGN KEY ("from_location_id","firm_id") REFERENCES "public"."locations"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_entries" ADD CONSTRAINT "daily_entries_to_location_firm_isolation_fk" FOREIGN KEY ("to_location_id","firm_id") REFERENCES "public"."locations"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trips" ADD CONSTRAINT "trips_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bills" ADD CONSTRAINT "bills_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tds_entries" ADD CONSTRAINT "tds_entries_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debit_notes" ADD CONSTRAINT "debit_notes_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_transactions" ADD CONSTRAINT "ledger_transactions_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opening_balances" ADD CONSTRAINT "opening_balances_party_firm_isolation_fk" FOREIGN KEY ("party_id","firm_id") REFERENCES "public"."parties"("id","firm_id") ON DELETE no action ON UPDATE no action;